/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookshop2;

import javax.swing.JOptionPane;

/**
 *
 * @author adarsh
 */
public class bookstock extends javax.swing.JFrame {

    /**
     * Creates new form bookstock
     */
    public bookstock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pricebook = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        bookname = new javax.swing.JTextField();
        bookauthor = new javax.swing.JTextField();
        bookcount = new javax.swing.JTextField();
        bookcategory = new javax.swing.JComboBox<>();
        savebook = new javax.swing.JButton();
        editbook = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pricetb = new javax.swing.JTextField();
        deletebook1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pricebook.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        pricebook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Id");
        pricebook.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 30, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Name");
        pricebook.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 42, -1, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Author");
        pricebook.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 42, -1, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("category");
        pricebook.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 42, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("Quantity");
        pricebook.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 42, -1, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Price");
        pricebook.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidActionPerformed(evt);
            }
        });
        pricebook.add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 86, 123, -1));
        pricebook.add(bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 84, 180, -1));

        bookauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookauthorActionPerformed(evt);
            }
        });
        pricebook.add(bookauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 84, 163, -1));
        pricebook.add(bookcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 81, 30));

        bookcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programming ", "DSA", "Applied Science", "Arts", "Commerce", " " }));
        pricebook.add(bookcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 84, 134, -1));

        savebook.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        savebook.setForeground(new java.awt.Color(255, 102, 102));
        savebook.setText("Add");
        savebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebookMouseClicked(evt);
            }
        });
        savebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebookActionPerformed(evt);
            }
        });
        pricebook.add(savebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        editbook.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        editbook.setForeground(new java.awt.Color(255, 102, 102));
        editbook.setText("Edit");
        pricebook.add(editbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        back.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 102, 102));
        back.setText("Go Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        pricebook.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pricebook.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1150, 374));
        pricebook.add(pricetb, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 100, 30));

        deletebook1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        deletebook1.setForeground(new java.awt.Color(255, 102, 102));
        deletebook1.setText("Delete");
        pricebook.add(deletebook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 181, 205));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("     Book Shop Management  ");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pricebook, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pricebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookidActionPerformed

    private void savebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebookActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0 );        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void savebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebookMouseClicked
      if(bookid.getText().isEmpty()||bookname.getText().isEmpty()||bookauthor.getText().isEmpty()||bookcategory.getSelectedIndex()==-1||pricetb.getText().isEmpty()||bookcount.getText().isEmpty())
      {
         JOptionPane.showMessageDialog(rootPane,"Some field are empty ","Error",1);
      }
      else
      {
          
      }
    }//GEN-LAST:event_savebookMouseClicked

    private void bookauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookauthorActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_bookauthorActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        adminchoice ob=new adminchoice();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookstock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField bookauthor;
    private javax.swing.JComboBox<String> bookcategory;
    private javax.swing.JTextField bookcount;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookname;
    private javax.swing.JButton deletebook1;
    private javax.swing.JButton editbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pricebook;
    private javax.swing.JTextField pricetb;
    private javax.swing.JButton savebook;
    // End of variables declaration//GEN-END:variables
}
