/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookshop2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author adarsh
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        options = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aboutUs = new javax.swing.JButton();
        userid = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        passwordl = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Serif", 1, 36)); // NOI18N
        jLabel1.setText("Login Form ");
        password.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select User---", "Admin", "Seller" }));
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });
        password.add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 181, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookshop2/loginicon-modified.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 21)); // NOI18N
        jLabel2.setText("Book Shop Management ");

        aboutUs.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        aboutUs.setForeground(new java.awt.Color(51, 51, 255));
        aboutUs.setText("About Us");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aboutUs)
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutUs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        password.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        userid.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        userid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        password.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 390, 40));

        signup.setBackground(new java.awt.Color(0, 181, 204));
        signup.setText("SignUp");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        password.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 140, 40));

        login.setBackground(new java.awt.Color(0, 181, 204));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        password.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 140, 40));

        jLabel4.setBackground(new java.awt.Color(0, 181, 205));
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 181, 205));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        password.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        passwordl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        passwordl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordlActionPerformed(evt);
            }
        });
        password.add(passwordl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 390, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookshop2/imagebook.png"))); // NOI18N
        password.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 190, 210));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Password");
        password.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 110, 30));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("E-mail");
        password.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here
       
    }//GEN-LAST:event_useridActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
     System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked
    private boolean validate_dataadmin(String id,String pass)
    {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/swinguser","root","Adarsh@123");
            java.sql.PreparedStatement pst=con.prepareStatement("select* from adminregistration where emailid=? and password=?");
            pst.setString(1,id);
            pst.setString(2,pass);
            java.sql.ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                
                return true;
            }
            else
            {
                return false;
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e);
            return false;
        }
        
    }
    
    private boolean validate_datauser(String id,String pass)
    {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/swinguser","root","Adarsh@123");
            java.sql.PreparedStatement pst=con.prepareStatement("select* from userregistration where  emailid=? and password=?");
            pst.setString(1,id);
            pst.setString(2,pass);
            java.sql.ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                
                return true;
            }
            else
            {
                return false;
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e);
            return false;
        }
        
    }
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

       String pass=passwordl.getText();
       String id=userid.getText();
       if(id.isEmpty()&& pass.isEmpty())
       {
           JOptionPane.showMessageDialog(rootPane, "Plase Enter User Id & Password");
       }
       else if(id.isEmpty())
       {
          JOptionPane.showMessageDialog(rootPane, "Plase Enter User Id");
                  
       }
       else if(pass.isEmpty())
       {
           JOptionPane.showMessageDialog(rootPane, "Plase Enter Password");
       }
       else
       {
            login log=new login();
            login logob=new login();
            String selectvalue= options.getSelectedItem().toString();
         
           
            if(selectvalue=="---Select User---" || selectvalue==""||selectvalue==" ")
            {
                JOptionPane.showMessageDialog(rootPane,"Select User  ","Error",1);
            }
            else if(selectvalue=="Admin")
            {
              String jid=userid.getText();
              String jpass=passwordl.getText();
              if(validate_dataadmin(jid,jpass))
              {
                
                  JOptionPane.showMessageDialog(rootPane,"Login Succesfully  ");
//                  adminchoice ob=new adminchoice();
//                  ob.setVisible(true);
                    adminchoice ob=new adminchoice();
                    ob.setVisible(true);
                    dispose();
                  
              }
              else
              {
                  
                  JOptionPane.showMessageDialog(rootPane,"Invalid UserId & Password");
                   userid.setText("");
                   passwordl.setText("");
                  
              }
            }
           else if(selectvalue=="Seller")
           {
              String jid=userid.getText();
              String jpass=passwordl.getText();
              if(validate_datauser(jid,jpass))
              {
                
                  JOptionPane.showMessageDialog(rootPane,"Login Succesfully  ");
                  sellerchoice ob=new sellerchoice();
                  ob.setVisible(true);
                  dispose();
                  
              }
              else
              {
                 
                  JOptionPane.showMessageDialog(rootPane,"Invalid UserId & Password");
                  
              }
           }
       }
    }//GEN-LAST:event_loginActionPerformed

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed
             
     
    }//GEN-LAST:event_optionsActionPerformed

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked

       String selectvalue= options.getSelectedItem().toString();
       if(selectvalue=="---Select User---" || selectvalue==""||selectvalue==" ")
       {
           JOptionPane.showMessageDialog(rootPane,"Some field are empty ","Error",1);
       }
       else if(selectvalue=="Admin")
       {
           signupuser ob=new signupuser();
           ob.setVisible(true);
           dispose();
       }
       else if(selectvalue=="Seller")
       {
           signupu ob=new signupu();
           ob.setVisible(true);
           dispose();
       }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_signupMouseClicked

    private void passwordlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutUs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JComboBox<String> options;
    private javax.swing.JPanel password;
    private javax.swing.JPasswordField passwordl;
    private javax.swing.JButton signup;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
