/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookshop2;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author adarsh
 */
public class userdata extends javax.swing.JFrame {

    /**
     * Creates new form userdata
     */
    public userdata() {
        initComponents();
        display();
    }
    Connection con=null;
   Statement st=null;
   java.sql.ResultSet rs=null;
   private void display()
   {
       try
       {
            con=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/swinguser","root","Adarsh@123");
            st=con.createStatement();
            rs=st.executeQuery("select* from userregistration");
            table.setModel(DbUtils.resultSetToTableModel(rs));
       }
       catch(Exception e)
       {
           
       }
   }
    private void resetfield()
    {
       username.setText("");
        umail.setText("");
        usermno.setText("");
        useraddhar.setText("");
        usrpass.setText("");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usermail = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        umail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        usermno = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        backto = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        deleteto = new javax.swing.JButton();
        saveto = new javax.swing.JButton();
        usrpass = new javax.swing.JTextField();
        editto = new javax.swing.JButton();
        resetto = new javax.swing.JButton();
        print = new javax.swing.JButton();
        useraddhar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        usermail.setBackground(new java.awt.Color(0, 181, 204));
        usermail.setForeground(new java.awt.Color(204, 153, 0));
        usermail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usermailMouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(0, 255, 204));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookshop2/reg1-modified.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel18.setText("Name");

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel19.setText("Email");

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel20.setText("Password");

        usermno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermnoActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel21.setText("Addhar");

        backto.setBackground(new java.awt.Color(204, 102, 0));
        backto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        backto.setText("Back");
        backto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtoMouseClicked(evt);
            }
        });
        backto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel22.setText("Mobile no");

        deleteto.setBackground(new java.awt.Color(204, 102, 0));
        deleteto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        deleteto.setText("Delete");
        deleteto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletetoMouseClicked(evt);
            }
        });

        saveto.setBackground(new java.awt.Color(204, 102, 0));
        saveto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        saveto.setText("Save");
        saveto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savetoMouseClicked(evt);
            }
        });
        saveto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetoActionPerformed(evt);
            }
        });

        editto.setBackground(new java.awt.Color(204, 102, 0));
        editto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        editto.setText("Edit");
        editto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edittoMouseClicked(evt);
            }
        });
        editto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edittoActionPerformed(evt);
            }
        });

        resetto.setBackground(new java.awt.Color(204, 102, 0));
        resetto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        resetto.setText("Reset");
        resetto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resettoMouseClicked(evt);
            }
        });
        resetto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resettoActionPerformed(evt);
            }
        });

        print.setBackground(new java.awt.Color(204, 102, 0));
        print.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        print.setText("Print");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usermailLayout = new javax.swing.GroupLayout(usermail);
        usermail.setLayout(usermailLayout);
        usermailLayout.setHorizontalGroup(
            usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usermailLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usermailLayout.createSequentialGroup()
                        .addComponent(saveto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(usermailLayout.createSequentialGroup()
                        .addComponent(backto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(resetto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(usermailLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usermailLayout.createSequentialGroup()
                        .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(usermailLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, usermailLayout.createSequentialGroup()
                                .addGap(17, 153, Short.MAX_VALUE)
                                .addComponent(deleteto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(usermailLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(usermailLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usermno)
                            .addComponent(umail)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(useraddhar)
                            .addComponent(usrpass))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        usermailLayout.setVerticalGroup(
            usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usermailLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(umail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usermno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(34, 34, 34)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(useraddhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(usrpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveto)
                    .addComponent(editto)
                    .addComponent(deleteto))
                .addGap(37, 37, 37)
                .addGroup(usermailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backto)
                    .addComponent(resetto)
                    .addComponent(print))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "EmailId", "Mobile no", "Addhar", "Password"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel23.setBackground(new java.awt.Color(0, 181, 204));
        jLabel23.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 181, 204));
        jLabel23.setText("X");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(usermail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usermail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usermnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usermnoActionPerformed

    private void backtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtoMouseClicked
        // TODO add your handling code here:
        adminchoice ob=new adminchoice();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_backtoMouseClicked

    private void backtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backtoActionPerformed

    private void deletetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletetoMouseClicked

        //                String bname=name.getText();
        //                String bid=id.getText();
        //                String bauthor=author.getText();
        //                String qnty=qunty.getText();
        //                String bprice =price.getText();
        //String category=(String) bcategory.getSelectedItem();
        if(username.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "All fields are Required");
        }
        else
        {
            try
            {
                String id=useraddhar.getText();

                con=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/swinguser","root","Adarsh@123");
                st=con.createStatement();
                String query="Delete from userregistration where addharno="+id;
                Statement Delete=con.createStatement();
                Delete.executeUpdate(query);
                int x=st.executeUpdate(query);
                JOptionPane.showMessageDialog(rootPane,"user Deleted ","Error",1);
                display();
                resetfield();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_deletetoMouseClicked

    private void savetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savetoMouseClicked

        String uname=username.getText();
        String mail=umail.getText();
        String umno=usermno.getText();
        String addhar=useraddhar.getText();
        String pass =usrpass.getText();
        if(username.getText().isEmpty()||umail.getText().isEmpty()||usermno.getText().isEmpty()||usrpass.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "All fields are Required");
        }
        else
        {
             try
            {
                con=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/swinguser","root","Adarsh@123");
                st=con.createStatement();
                String query="INSERT INTO  userregistration values('"+ uname +"','"+mail +"','"+umno+"','"+addhar+"','"+pass+"')";
                int x=st.executeUpdate(query);
                if(x!=0)
                {
                    JOptionPane.showMessageDialog(rootPane,"Saved","Error",1);

                    display();
                    resetfield();
                }
                con.close();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_savetoMouseClicked

    private void savetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savetoActionPerformed

    private void edittoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edittoMouseClicked
        
        String uname=username.getText();
        String mail=umail.getText();
        String umno=usermno.getText();
        String addhar=useraddhar.getText();
        String pass =usrpass.getText();
        if(username.getText().isEmpty()||umail.getText().isEmpty()||usermno.getText().isEmpty()||usrpass.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "All fields are Required");
        }
        else
        {
            try
            {
                con=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/swinguser","root","Adarsh@123");
                st=con.createStatement();
                String query="update userregistration set name='"+uname+"', emailid='"+mail+"', mobileno='"+umno+"',  password='"+pass+"' where addharno="+addhar;
                Statement Delete=con.createStatement();
                Delete.executeUpdate(query);
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(rootPane,"Book Details Updated ","Error",1);
                display();
               resetfield();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_edittoMouseClicked

    private void edittoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edittoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edittoActionPerformed

    private void resettoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resettoMouseClicked
        resetfield();
    }//GEN-LAST:event_resettoMouseClicked

    private void resettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resettoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resettoActionPerformed

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_printMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void usermailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usermailMouseClicked
        //        sellerchoice ob= new sellerchoice();
        //        ob.setVisible(true);
        //        dispose();
    }//GEN-LAST:event_usermailMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=( DefaultTableModel)
        table.getModel();
        int myindex=table.getSelectedRow();
       username.setText(model.getValueAt(myindex, 0).toString());
        umail.setText(model.getValueAt(myindex, 1).toString());
        usermno.setText(model.getValueAt(myindex, 2).toString());
        useraddhar.setText(model.getValueAt(myindex, 3).toString());
        usrpass.setText(model.getValueAt(myindex, 4).toString());
        
        
       
    }//GEN-LAST:event_tableMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel23MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backto;
    private javax.swing.JButton deleteto;
    private javax.swing.JButton editto;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    private javax.swing.JButton resetto;
    private javax.swing.JButton saveto;
    private javax.swing.JTable table;
    private javax.swing.JTextField umail;
    private javax.swing.JTextField useraddhar;
    private javax.swing.JPanel usermail;
    private javax.swing.JTextField usermno;
    private javax.swing.JTextField username;
    private javax.swing.JTextField usrpass;
    // End of variables declaration//GEN-END:variables
}
